### ISSUE TITLE
enable web access it showed error

### ISSUE THREAD

**Issue by shengkaixuan** [ramonvc/freegpt-webui#10]
who is the ceo of twitter?

{"_action":"_ask","error":"an error occurred HTTPSConnectionPool(host='ddg-api.herokuapp.com', port=443): Max retries exceeded with url: /search?query=who+is+the+ceo+of+twitter%3F&limit=5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021F620C2650>, 'Connection to ddg-api.herokuapp.com timed out. (connect timeout=None)'))","success":false}

how to deal with this kind error??

**Comment by ramonvc** [comment]
The issue seems to be related to your connection. Something in it is blocking a response from the API hosted on herokuapp. You can directly test the API in your browser using the URL:
<br>
`https://ddg-api.herokuapp.com/search?query=who+is+the+ceo+of+twitter%3F&limit=1`
<br>
![image](https://github.com/ramonvc/freegpt-webui/assets/13617054/1f8fb466-be0a-43ce-ae3a-caad9e8a68ce)
In my case, it returns the query "who is the ceo of twitter" with a limit of "1" search. If you test this and get an error directly in your browser, it's certain that it's a problem with your connection and you can try using a proxy or DNS to work around it, or implement another search API.
