### ISSUE TITLE
File downloading and saving?

### ISSUE THREAD

**Issue by yemix** [ramonvc/freegpt-webui#132]
I used GPT-4 and activated Web Access. I said can u go to this GitHub Site (https://github.com/exampleUser/exampleRepository) and send me the Link of the File (example.txt).
It said it's not possible cause of no Web Access. Im wrong with the Web Access Feature or do I need an other model. Or is the Feature buggy?

**Comment by yemix** [comment]
I tried it with Claude, there is it working. Can u make a temp Folder, so the AI can save Files and send me that in the Chat?

**Comment by ramonvc** [comment]
The web access is just an API that returns some web search results and adds to the prompt to improve the model's response. For the model to have full access to the web, it must come from the company that owns the model. In Claude's case, the Web access comes from the model itself, so much so that it even works with "web access" disabled.

**Comment by yemix** [comment]
Ah i understand now, thanks. Im waiting for features like file sharing or login to accounts and do actions, is there now a model official or unofficial?
