### ISSUE TITLE
Problem with GPT-4

### ISSUE THREAD

**Issue by Em1tSan** [ramonvc/freegpt-webui#6]
#5 
```
            # Generate response
            response = ChatCompletion.create(model=model, stream=True,
                                             messages=messages, provider=g4f.Provider.Forefront)

```
This is a code snippet from file backend.py

If I understand correctly, this is the reason why any request goes to the Forefront provider, regardless of the selected model. This is why when we select GPT-4, we are actually using the same GPT-3.5 Turbo.

If you change the code to 

```
response = ChatCompletion.create(model=model, stream=True,
                                             messages=messages)
```

Then the Provider is taken from the file g4f/__init__.py:

```
class gpt_35_turbo:
        name: str = 'gpt-3.5-turbo'
        base_provider: str = 'openai'
        best_site: Provider.Provider = Provider.Forefront

    class gpt_4:
        name: str = 'gpt-4'
        base_provider: str = 'openai'
        best_site: Provider.Provider = Provider.Bing
```

And now, the request is sent through the Provider Bing. But for some reason it's broken and I couldn't get any response.

**Comment by ramonvc** [comment]
In this project, I only use the forefront provider since it was the only one that provided a stable response from both GPT-3.5 and GPT-4, as mentioned in the readme.md file of this project. The G4F API is an embedded API of [gpt4free](https://github.com/xtekky/gpt4free).

However, you can visit the original API project and find a solution to use other providers such as Bing. I tested some others like You and Phind, and they also worked very well, but I preferred forefront.

Regarding the issue of the model passing incorrectly, you were right. I found an error where it was fixed to always use the 'gpt-4' model, so none of the requests used 'GPT-3.5-turbo', even when selected haha.

![image](https://github.com/ramonvc/freegpt-webui/assets/13617054/8ce28079-3431-4a1d-bfc7-2720478ebd09)

I'm sorry I couldn't fix this for you. Maybe I'll try using Bing when I have more time and help you with that. Thank you for supporting the project. 

I removed the other providers to avoid further confusion https://github.com/ramonvc/freegpt-webui/commit/1fc65b1ca73a188abcc770953e0813ada6acabe5.
