### ISSUE TITLE
What happened with gpt-4

### ISSUE THREAD

**Issue by Glega** [ramonvc/freegpt-webui#90]
I think GPT-4 is actually GPT-3.

**Comment by ramonvc** [comment]
I think giraffes are holograms.

**Comment by Glega** [comment]
most likely I'm wrong, but it seemed to me that the quality of the gpt-4 text two weeks ago is very different from today's version. even in Russian there are gross errors, although before that everything was great.

**Comment by ramonvc** [comment]
OpenAI is severely limiting the power of GPT because of jailbreaks, which allowed the AI ​​to answer anything. Bing itself doesn't even text school anymore. These barriers end up limiting part of the technology's responses and this is linked to the differences in responses, even with the same model. 

Another reason is that I am using two versions of GPT-4 in my website, the 'gpt-4' model and also the 'gpt-4-0613', depending on the limitations the backend makes the choice itself and that also makes differences in the answers.

**Comment by ramonvc** [comment]
> The GPT4 in your site sometimes response like gpt3.5 @ramonvc


Depending on the demand and status of GPT-4, the API fallback may redirect to GPT-3.5. But it's pretty hard.
